export const products = [
    {
        id: "g1",
        name: "Mezcladora Monomando Alta",
        category: "griferia",
        price: 3499,
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=2070&auto=format&fit=crop",
        description: "Grifería de lujo con acabado negro mate, ideal para lavabos sobre encimera.",
        featured: true,
    },
    {
        id: "g2",
        name: "Grifo de Pared Dorado",
        category: "griferia",
        price: 4200,
        image: "https://images.unsplash.com/photo-1616486338812-3eec5594a9b0?q=80&w=1932&auto=format&fit=crop",
        description: "Elegancia pura con nuestro grifo de pared en acabado oro cepillado.",
        featured: true,
    },
    {
        id: "t1",
        name: "Tina Freestanding Oval",
        category: "tinas",
        price: 25000,
        image: "https://images.unsplash.com/photo-1543489822-c49534f3271f?q=80&w=2070&auto=format&fit=crop",
        description: "Tina ergonómica de acrílico de alta calidad, diseño minimalista moderno.",
        featured: true,
    },
    {
        id: "t2",
        name: "Tina Rectangular Spa",
        category: "tinas",
        price: 32000,
        image: "https://images.unsplash.com/photo-1600607686527-6fb886090705?q=80&w=2000&auto=format&fit=crop",
        description: "Amplia tina rectangular perfecta para dos personas, experiencia spa en casa.",
        featured: false,
    },
    {
        id: "r1",
        name: "Panel de Ducha Hidromasaje",
        category: "regaderas",
        price: 8900,
        image: "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?q=80&w=2070&auto=format&fit=crop",
        description: "Panel completo con jets de hidromasaje y ducha de lluvia.",
        featured: false,
    },
    {
        id: "r2",
        name: "Regadera de Techo Lluvia",
        category: "regaderas",
        price: 5600,
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=2070&auto=format&fit=crop",
        description: "Experiencia de lluvia natural con esta regadera de techo de 40cm.",
        featured: true,
    },
];
